name: JD_Sign_Action

on:
  repository_dispatch:
  release:
    types: published
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: 0 20 * * *
  watch:
    types: started
    
env:
  JD_COOKIE: ${{ __jdu=1601110691217688327403; shshshfpa=2181609f-6cd7-7858-b720-e80b787d0464-1601110692; shshshfpb=oYs%2FYJ34eu28uk%20U3TbTMdw%3D%3D; pinId=HC0n4ijT6pifqmvQGVe7HAuYm7hZnBe2; __jdv=76161171|cn.bing.com|-|referral|-|1611489091105; areaId=15; ipLoc-djd=15-1158-46341-0; o2State={%22webp%22:true%2C%22lastvisit%22:1611489091600}; TrackID=1Tsoj0DkmkMTzETVCDHsGH0gDhAYw7Zr1kqP2LNqprRAZiKyIxAsuKnh9DNnalhPHuuWuD3aLPbqeGb-lW5Uigg1uVvUUHdhOfhIpCYXzzlNKwqpbXS_xIu-XiSlhQtoqbrO91MEUfYTbRA1DpCTVmQ; pin=%E9%AA%84%E9%98%B3%E4%BC%BC%E7%81%AB12138; unick=%E9%AA%84%E9%98%B3%E4%BC%BC%E7%81%AB12138; ceshi3.com=103; _tp=f3YXhPHxYnvnfygFMqAOpyIy9dDQvhqlDr4kN67PY8msdC3LavpKOFBn447Xl9x8; _pst=%E9%AA%84%E9%98%B3%E4%BC%BC%E7%81%AB12138; user-key=ab0747ba-6e6b-4f94-b3d2-a07e5fab2f0a; cn=14; __jda=122270672.1601110691217688327403.1601110691.1607954754.1611489091.15; __jdc=122270672; 3AB9D23F7A4B3C9B=FHW2ZAJ6EIDOC5UDRDC4FSG5AFXZ5BNDHNXE5ZFDEFIHZCR3XE3LB4SPX47XR6FX76ECG2PW4DM4TKZQBFN7FYPDW4; thor=A0F6EDAC55868B097666D1D671958723029AC1A0AD93D760A575630B888E0D8DC03B93467BBDCFA112B981894CE383C4DB7D6D7B09064449C5D99DB37B27CF4A60E210B757BE0FEB90E29E04C9897953B8861E5D0E9AB4BE6383041F9EA14FEA9873E804A0E57EFF0F3311CB69B1B1CC79F1E6D239E20972A083DE0AACF10DA1D4BA4A1C3C703228CD1267F0226EB074; shshshfp=de2c51c6258c123179f4429d4e3cab14; }}
  JD_DUAL_COOKIE: ${{ secrets.JD_DUAL_COOKIE }}
  PUSH_KEY: ${{ SCU154499T56d647fe5526308c6a7ada11a96f671d600d62d2c4703 }}
  UPLOAD_BESULT_DIR: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                
            - name: Run install
              run: npm install
              
            - name: Run Script
              run: node jd_sign.js
                
            - name: Upload result file
              uses: actions/upload-artifact@master
              if: env.UPLOAD_BESULT_DIR == 'true'
              with:
                name: result
                path: ./*.txt


